
package com.soap.ws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Add", targetNamespace = "http://services")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Add {


    /**
     * 
     * @param a
     * @param b
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "addReturn", targetNamespace = "http://services")
    @RequestWrapper(localName = "add", targetNamespace = "http://services", className = "com.soap.ws.client.Add_Type")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://services", className = "com.soap.ws.client.AddResponse")
    public int add(
        @WebParam(name = "a", targetNamespace = "http://services")
        int a,
        @WebParam(name = "b", targetNamespace = "http://services")
        int b);

}
