
package com.soap.ws.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AddService", targetNamespace = "http://services", wsdlLocation = "http://localhost:8080/Calculator_WS/services/Add?wsdl")
public class AddService
    extends Service
{

    private final static URL ADDSERVICE_WSDL_LOCATION;
    private final static WebServiceException ADDSERVICE_EXCEPTION;
    private final static QName ADDSERVICE_QNAME = new QName("http://services", "AddService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/Calculator_WS/services/Add?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ADDSERVICE_WSDL_LOCATION = url;
        ADDSERVICE_EXCEPTION = e;
    }

    public AddService() {
        super(__getWsdlLocation(), ADDSERVICE_QNAME);
    }

    public AddService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ADDSERVICE_QNAME, features);
    }

    public AddService(URL wsdlLocation) {
        super(wsdlLocation, ADDSERVICE_QNAME);
    }

    public AddService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ADDSERVICE_QNAME, features);
    }

    public AddService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AddService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Add
     */
    @WebEndpoint(name = "Add")
    public Add getAdd() {
        return super.getPort(new QName("http://services", "Add"), Add.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Add
     */
    @WebEndpoint(name = "Add")
    public Add getAdd(WebServiceFeature... features) {
        return super.getPort(new QName("http://services", "Add"), Add.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ADDSERVICE_EXCEPTION!= null) {
            throw ADDSERVICE_EXCEPTION;
        }
        return ADDSERVICE_WSDL_LOCATION;
    }

}
